name: new release check

on:
  release:
    types:
      - created
    tags:
      - '*.*.*'

jobs:
  check:
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v2

    - name: Extract tag reference
      run: |
        TAG_REF=(${GITHUB_REF//\// })
        TAG_REF=${TAG_REF[2]}

        echo "Extracted reference: $TAG_REF"
        echo "TAG_REF=$TAG_REF" >> $GITHUB_ENV

    - name: Execute check for tag
      run: |
        ./check_new_release.sh $TAG_REF
