name: new release check

on:
  release:
    types:
      - created
    tags:
      - '*.*.*'

jobs:
  check:
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v2

    - name: Execute check for tag
      run: |
        ./check_new_release.sh $GITHUB_REF
